name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - name: Install dependencies
        run:  |
          Rscript -e "install.packages('devtools')"
          Rscript -e "install.packages('tidyverse')"
          Rscript -e "install.packages('remotes')"
          Rscript -e "library(tidyverse)"
          Rscript -e "remotes::install_deps()"
      - name: Check
        run: |
          Rscript -e "devtools::check()"
